name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0' # من الأفضل تحديد نطاق أوسع للتوافق

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.1.1
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_storage: ^11.9.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_lints: ^3.0.0 # تم تعديل الإصدار ليكون متوافقًا بشكل عام
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
