name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0' # من الأفضل تحديد نطاق أوسع للتوافق

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  flutter_localization: ^0.3.3
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  my_fatoorah_payment_flutter: ^1.1.3
  myfatoorah_flutter: ^3.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^3.0.0 # تم تعديل الإصدار ليكون متوافقًا بشكل عام
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
