name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0' # من الأفضل تحديد نطاق أوسع للتوافق

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.2
  crypto: ^3.0.6
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_local_notifications: ^17.2.1
  flutter_localization: ^0.3.3
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  myfatoorah_flutter: ^3.1.0
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^3.0.0 # تم تعديل الإصدار ليكون متوافقًا بشكل عام
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
