// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIOoveEG08wzogQyirhP7tfSZCiCudABo',
    appId: '1:70374124423:android:f5f4c8a36511c9262a4122',
    messagingSenderId: '70374124423',
    projectId: 'raval-store-app',
    storageBucket: 'raval-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXntmPZ54aH3On_z3wAdnDiliXp7BT7M',
    appId: '1:70374124423:ios:d3e92342ef4fbc672a4122',
    messagingSenderId: '70374124423',
    projectId: 'raval-store-app',
    storageBucket: 'raval-store-app.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNEkYFK7GbGMI95IQ2l7KuqHarHo70-A',
    appId: '1:70374124423:web:375eb7b1356115b82a4122',
    messagingSenderId: '70374124423',
    projectId: 'raval-store-app',
    authDomain: 'raval-store-app.firebaseapp.com',
    storageBucket: 'raval-store-app.firebasestorage.app',
    measurementId: 'G-3SCHCPXL4Y',
  );
}
